app_username: strava_username_or_email
app_password: strava_password
strava:
  client_id: 'app_client_id'
  client_secret: '#########'
  refresh_token: '#########'
  access_token: "############"
  expires_at: 1756780223
